SET IDENTITY_INSERT [dbo].[medicine] ON
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (1, N'acifix')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (2, N'anustat')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (3, N'napa')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (4, N'ace')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (5, N'fexo')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (6, N'emistate')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (7, N'omegut')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (8, N'max pro')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (9, N'coversyl')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (10, N'zolax')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (11, N'prosan')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (12, N'respira')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (13, N'antazol nasal drop')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (14, N'terbex')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (15, N'sparlin')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (16, N'synroid')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (17, N'tofen')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (18, N'tolmus')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (19, N'turbocef')
INSERT INTO [dbo].[medicine] ([medicineid], [medicinename]) VALUES (20, N'ribox')
SET IDENTITY_INSERT [dbo].[medicine] OFF
