SET IDENTITY_INSERT [dbo].[person] ON
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (1, N'king', 30, N'male', N'bpv', N'01711090201')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (2, N'clark', 29, N'male', N'bpv', N'01711090203')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (3, N'joey', 29, N'male', N'bpv', N'01711090205')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (4, N'rose', 29, N'male', N'bnv', N'01711090207')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (5, N'scott', 27, N'male', N'bnv', N'01711090209')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (6, N'smith', 27, N'male', N'apv', N'01711090211')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (7, N'wilson', 25, N'male', N'apv', N'01711090212')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (8, N'tomas', 25, N'male', N'anv', N'01711090213')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (9, N'jerry', 24, N'female', N'anv', N'01834101212')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (10, N'daisy', 26, N'female', N'opv', N'01834101214')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (11, N'monica', 28, N'female', N'opv', N'01834101216')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (12, N'aniston', 24, N'female', N'onv', N'01834101218')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (13, N'jon', 25, N'male', N'onv', N'01834101222')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (14, N'jim', 15, N'male', N'bpv', N'01834101224')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (15, N'arya', 13, N'female', N'bpv', N'01834101232')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (16, N'bran', 15, N'male', N'bpv', N'01987213511')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (17, N'sansa', 17, N'female', N'apv', N'01987213512')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (18, N'robert', 19, N'male', N'apv', N'01987213513')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (19, N'ned', 10, N'male', N'apv', N'01987213516')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (20, N'stark', 11, N'male', N'bnv', N'01987213519')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (21, N'nancy', 27, N'female', N'bpv', N'01987654521')
INSERT INTO [dbo].[person] ([personid], [name], [age], [gender], [bloodgroup], [phone]) VALUES (22, N'portman', 28, N'female', N'bpv', N'01876212121')
SET IDENTITY_INSERT [dbo].[person] OFF
