SET IDENTITY_INSERT [dbo].[disease] ON
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (1, N'sore throat')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (2, N'ear pain')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (3, N'urinary tract infection')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (4, N'skin infection')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (5, N'bronchitis')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (6, N'bronchiolitis')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (7, N'coronary artery disease')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (8, N'angina')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (9, N'heart attack')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (10, N'heart failure')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (11, N'dystonia')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (12, N'cerebral palsy')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (13, N'neuropathy')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (14, N'fever')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (15, N'cough and cold')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (16, N'asthma')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (17, N'cancer')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (18, N'diabetes')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (19, N'digestion')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (20, N'migrain')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (21, N'sleep')
INSERT INTO [dbo].[disease] ([diseaseid], [diseasename]) VALUES (22, N'anemia')
SET IDENTITY_INSERT [dbo].[disease] OFF
